---
homebrew_packages_list:
  - fd
  - difftastic
  - just
  - tree
  - nvim
  - git
  - gnupg
  - jq
  - "n"
  - pinentry-mac
  - protobuf
  - ripgrep
  - sqlite
  - terraform
  - wget
  - coreutils
  - bat
  - fzf
  - stow
  - util-linux
  - tmux
  - htop
  - autoconf
  #   - wxmac # to be revised
  - pre-commit
  - git-delta
  - neovim
  - starship
  - dust
  - bottom
  - topgrade
  - tokei
  - vale # prose linter for docs
  - espanso
  - deskpad
  - gitui
  - helix
  - deno
  - pearcleaner
  - bruno
  - zoxide

cask_packages:
  - alacritty
  - amethyst
  - handbrake
  - visual-studio-code@insiders
  - hiddenbar
  - ghostty
  - iina
  - zed

homebrew_taps:
  - espanso/espanso
